### ISSUE TITLE
Unable to import neutcurve

### ISSUE THREAD

**Issue by ratnadeep1982** [jbloomlab/neutcurve#25]
While importing neutcurve, I get the following error:

>>> import neutcurve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/neutcurve/__init__.py", line 22, in <module>
    from neutcurve.curvefits import CurveFits  # noqa: F401
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/neutcurve/curvefits.py", line 12, in <module>
    import dmslogo.facet
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/dmslogo/__init__.py", line 23, in <module>
    from dmslogo.logo import draw_logo  # noqa: F401
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/dmslogo/logo.py", line 43, in <module>
    matplotlib.font_manager.fontManager.addfont(_fontfile)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1100, in addfont
    prop = ttfFontProperty(font)
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/font_manager.py", line 464, in ttfFontProperty
    weight = int(get_weight())
  File "/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/font_manager.py", line 447, in get_weight
    font.get_ps_font_info()["weight"].replace(" ", "") or "")
TypeError: tuple indices must be integers or slices, not str

I am using Python 3.6.8 on a MacOS Mojave

**Comment by jbloom** [comment]
What version of `matplotlib` do you have?
```
import matplotlib
print(matplotlib.__version__)
```

**Comment by ratnadeep1982** [comment]
Thanks for your response. My Matplotlib version is 3.3.3

**Comment by jbloom** [comment]
Apologies, but I'm not able to reproduce the problem on my computer even using `matplotlib` version 3.3.3 (which is where the error is thrown). I'm using Python 3.7, but that is only difference.

It may be something about your particular Mac, where as we are just testing on Linux. But without being able to reproduce the error, I can't troubleshoot it.

**Comment by ratnadeep1982** [comment]
I keep getting the same error even after updating Python to the latest version (3.9) and creating a new conda environment. 

Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import neutcurve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/neutcurve/__init__.py", line 22, in <module>
    from neutcurve.curvefits import CurveFits  # noqa: F401
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/neutcurve/curvefits.py", line 12, in <module>
    import dmslogo.facet
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/dmslogo/__init__.py", line 23, in <module>
    from dmslogo.logo import draw_logo  # noqa: F401
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/dmslogo/logo.py", line 43, in <module>
    matplotlib.font_manager.fontManager.addfont(_fontfile)
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1100, in addfont
    prop = ttfFontProperty(font)
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib/font_manager.py", line 464, in ttfFontProperty
    weight = int(get_weight())
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib/font_manager.py", line 447, in get_weight
    font.get_ps_font_info()["weight"].replace(" ", "") or "")
TypeError: tuple indices must be integers or slices, not str

I am totally at a loss as to why this may be happening

**Comment by jbloom** [comment]
Can you post your entire `conda` environment specification YAML file (create with `conda env export > environment.yml`) for the environment giving this error and I'll see if I can reproduce it (and then try to fix it).

**Comment by ratnadeep1982** [comment]
Here it is:

name: py39
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.11.8=h033912b_0
  - certifi=2020.11.8=py39h6e9494a_0
  - libcxx=11.0.0=h4c3b8ed_1
  - libffi=3.3=h74dc148_1
  - ncurses=6.2=h2e338ed_4
  - openssl=1.1.1h=haf1e3a3_0
  - pip=20.3=pyhd8ed1ab_0
  - python=3.9.0=h4f09611_5_cpython
  - python_abi=3.9=1_cp39
  - readline=8.0=h0678c8f_2
  - setuptools=49.6.0=py39h2c36a5b_2
  - sqlite=3.34.0=h17101e1_0
  - tk=8.6.10=hb0a8c7a_1
  - tzdata=2020d=h516909a_0
  - wheel=0.36.0=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h7795811_1010
  - pip:
    - cycler==0.10.0
    - dmslogo==0.5.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.3
    - neutcurve==0.5.3
    - numpy==1.19.4
    - pandas==1.1.4
    - pillow==8.0.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - scipy==1.5.4
    - six==1.15.0
    - xlrd==1.2.0
prefix: /anaconda3/envs/py39

**Comment by jbloom** [comment]
@ratnadeep1982, I'm sorry, but I can't reproduce the error. I built the exact `conda` environment above from your YAML specs on my Mac, and I can import `neutcurve` just fine. The error message seems to be coming from `matplotlib` parsing the font files, so I suspect it has something to do with how the fonts are installed on your Mac. I'd suggest maybe trying a different computer (possibly Linux or at least a different Mac) if you have one available.

I can't really troubleshoot further if I can't reproduce the error.

**Comment by AoifeHughes** [comment]
Hi, 

I just opened an issue, but googling has brought me to here. This is the exact same issue that I'm having on both my macbook and desktop.

**Comment by jbloom** [comment]
See comments above, I can't reproduce this in my computer. I think it has something to do with how font files are installed on your computer, but I can't troubleshoot if I can't reproduce it. Do you have an option of using some other computer such as a Linux machine?

**Comment by jbloom** [comment]
Should be fixed in #30, which is version 0.5.5.
